default_stages: [commit]
repos:
  # >>>>>>>>>>>>>>>>>>>>> basic <<<<<<<<<<<<<<<<<<<< #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      # - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # - id: double-quote-string-fixer
      - id: end-of-file-fixer
      # - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: sort-simple-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.2.5"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: "v3.13.0"
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: "v3.7.0-4"
    hooks:
      - id: shfmt
        args: ["-w", "-i", "2", "-s", "-l", "-ci"]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: "1.7.1"
    hooks:
      - id: nbqa-ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.13"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --no-cache]
