[tool.ruff]
select = ["E", "F", "B", "Q", "I", "UP"]
line-length = 100
target-version = "py311"

[tool.ruff.per-file-ignores]

[tool.yapf]
based_on_style = "google"
column_limit = 100

[tool.black]
line-length = 100
target-version = ['py311']
